# Generated by Django 4.2 on 2023-04-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_created_message_is_read_message_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("created",)},
        ),
    ]
