# Generated by Django 4.2 on 2023-04-13 14:16
from django.core.management import call_command
from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    call_command("loaddata", "fixture_data.json")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_message_options"),
    ]

    operations = [RunPython(func)]
